// Journey to the West S1 C1｜石猴出世 — Story Blocks mission guides.
// Split out of curriculumGuides.ts to keep every file under the 1000-line
// hard rule in rules/file-organization.md. curriculumGuides.ts stays the
// public module and re-exports the assembled catalogue.

import type { StoryMission } from './types';

export const JTW_C1_MISSIONS: Record<string, StoryMission> = {
  'jtw-s1-c1-p4': {
    mode: 'complete',
    lessonId: 'jtw-s1-c1-p4',
    hero: {
      name: '石猴',
      role: '花果山的新朋友',
      asset: '/story-blocks/journey-to-the-west/characters/stone-monkey/neutral-v01.png',
    },
    eyebrow: '西游记 · 第一章 · Build 1',
    title: '搭出完整出世链',
    storyPages: [
      {
        emoji: '🍃🐒',
        title: '排练说得通了，舞台还安静着',
        body: '草地上的排练大家都看懂了，可仙石旁的故事舞台还是安静的。石猴的轮廓藏在光后，群猴只能看见一块微微发亮的石头。',
        speaker: '石猴',
        dialogue: '刚才我们用身体演过了。现在要让舞台也照这个顺序做。',
        scene: 1,
      },
      {
        emoji: '🧩🔍',
        title: '候选区里有真有假',
        body: '候选动作里，Grow 会让角色变大，Turn 会让角色转身——它们都能运行，却回答不了眼前的问题。眼前需要的是：提示、出现、第一次动作和问候。',
        speaker: '群猴',
        dialogue: '别急着按开始！先告诉我们：光亮之后会看见什么？',
        scene: 3,
      },
      {
        emoji: '🔔👀🦘💬',
        title: '把四块接在 Start 和 End 之间',
        body: '按故事顺序放好 Chime、Show、Hop 1、Say「你好，我刚刚来到这里。」，每接上一块，舞台就多了一段可以解释的因果。',
        speaker: '石猴',
        dialogue: '先让石头出声，再让大家看见我，然后跳，最后问好。',
        scene: 4,
        blocks: ['🔔 Chime · 👀 Show', '🦘 Hop 1 · 💬 Say'],
      },
    ],
    partnerLine: '四张顺序卡在你手里，石猴等着你把排练搬上真正的舞台！',
    mission:
      'Start 和 hide 已经放好。从候选里选出 Chime、Show、Hop 1、Say「你好，我刚刚来到这里。」按顺序接上，最后以 End 收尾，再按 Go 运行你自己的程序。',
    question: '哪一块必须放在 Hop 和 Say 之前，伙伴才能看见是谁？',
    choices: [],
    retry: '想想排练的约定：还没有 Show，大家看不到石猴。',
    successTitle: '出世链搭好了，可以运行了！⭐',
    success: '你自己搭出了完整的出世顺序。按 Go，看每一步被大家看见。',
    fixTitle: '把出世链搭完整',
    fixPrompt: '关掉这张卡，去真正的工作区放上 Chime → Show → Hop 1 → Say，最后接 End。',
    workspaceIntro: '石猴还在等你把四块动作真正接到程序里。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '搭建时间：在 hide 后面按顺序接上 Chime、Show、Hop 1 和 Say。',
      watch: '看你自己的积木从左到右运行。',
      sayFirst: '问候声先响了，大家却没看见我。把 Show 放到前面。',
      sayThen: '最后，我说「你好，我刚刚来到这里。」💬',
      hopFirst: '大家看见我之后，我先跳一下！🦘',
      hopThen: 'Hop 排在 Say 后面了。先跳，再问好。',
      retry: '出世的句子还没说完。把四块动作都接上，再以 End 收尾。',
      fix: '在真正的工作区里搭积木——没有任何按钮会替你完成。',
      test: '出世链完整了。按 Go 试试你的程序！',
      saving: '成功了！我在保存你搭的积木……',
      complete: '你亲手让大家看见了石猴的出世！',
    },
    logicSteps: [
      { icon: '🔔', label: 'Chime', order: '提示' },
      { icon: '👀', label: 'Show', order: '出现' },
      { icon: '🦘', label: 'Hop 1', order: '动作' },
      { icon: '💬', label: 'Say', order: '问候' },
    ],
    logicWhy: '积木从左到右运行：先有提示，再被看见，然后行动，最后问候——每个可见变化都来自顺序。',
    completionTitle: 'Build 1 完成！🐒',
    completion: '你选出四块真动作、按故事顺序接好并真实运行：仙石亮起，石猴出现、跳到石台中央，向伙伴问好。',
    completionSteps: [
      { icon: '🔔', label: '仙石出声', order: '先' },
      { icon: '👀', label: '石猴出现', order: '再' },
      { icon: '💬', label: '开口问好', order: '最后' },
    ],
    completionWhy: 'Show 排在 Hop 和 Say 之前，所以每个动作都被伙伴看见，没有动作躲在空中发生。',
    next: '群猴问：你会先跳过来，还是先和我们说话？下一个 Part 由你决定第一次动作。',
  },

  // Journey to the West S1/C1-P5 — Build 2: the greeting-order CHOICE. Both
  // orders are valid; the child chooses which side of the Stone Monkey the
  // audience meets first and explains the choice from the story.
  'jtw-s1-c1-p5': {
    mode: 'personal-ship',
    lessonId: 'jtw-s1-c1-p5',
    hero: {
      name: '石猴',
      role: '花果山的新朋友',
      asset: '/story-blocks/journey-to-the-west/characters/stone-monkey/neutral-v01.png',
    },
    eyebrow: '西游记 · 第一章 · Build 2',
    title: '两种真诚的问候',
    storyPages: [
      {
        emoji: '🐒✨',
        title: '还差一个属于他的选择',
        body: '石猴已经站在大家面前，可第一次见面还差一个属于他的选择：先跳过去，还是先问好？',
        speaker: '石猴',
        dialogue: '两种都真诚。哪一种更像你想介绍的我？',
        scene: 1,
      },
      {
        emoji: '🦘💬',
        title: '版本 A：先跳，再问好',
        body: '石猴先轻快地跳到草地上，再笑着说：“你好，我也是刚刚认识这个世界。”群猴先被他的活力吸引，随后听懂他的来意。',
        speaker: '群猴',
        dialogue: '他好有活力！',
        scene: 3,
      },
      {
        emoji: '💬🦘',
        title: '版本 B：先问好，再跳',
        body: '石猴先留在石台上，轻声说：“你们好，我可以过来吗？”等群猴点头，他才跳近一步。群猴先感到被尊重，随后发现他也很爱行动。',
        speaker: '群猴',
        dialogue: '他真有礼貌。',
        scene: 4,
        blocks: ['🦘 Hop → 💬 Say', '💬 Say → 🦘 Hop'],
      },
    ],
    partnerLine: '出世链已经稳了。这一次，顺序由你决定——用故事理由选，别随便点。',
    mission:
      '前面的 Start、hide、Chime、Show 已经放好。把 Hop 1 和一句预设问候按「你想让伙伴先看见哪一面」的顺序接上，运行两种版本比较，再留下你选定的那一版。',
    question: '伙伴会先看见活力，还是先听见礼貌？这由哪两块的顺序决定？',
    choices: [],
    retry: '交换 Hop 和 Say 再运行一次，比较群猴先感受到什么。',
    successTitle: '你的问候方式已经选好！⭐',
    success: '两个版本都真诚。你用故事理由留下了自己的那一版。',
    fixTitle: '把问候搭完整',
    fixPrompt: '关掉这张卡，把 Hop 1 和一句预设问候接到 Show 后面，试试两种顺序。',
    workspaceIntro: '石猴在等你决定：先让大家看见活力，还是先听见礼貌。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '把 Hop 1 和预设问候按你选的顺序接上；两种顺序都可以运行比较。',
      watch: '看这一版里，伙伴先感受到什么。',
      sayFirst: '先问好——群猴先感到被尊重。',
      sayThen: '问候在跳之后——大家先看见活力。',
      hopFirst: '先跳——群猴先看见活力！',
      hopThen: '跳在问候之后——大家先听见礼貌。',
      retry: '问候还没搭完。Hop 1 和一句预设问候都要接上，以 End 收尾。',
      fix: '在真正的工作区里交换顺序比较——没有按钮会替你选择。',
      test: '这一版搭好了。按 Go 看伙伴的反应！',
      saving: '我在保存你选定的问候方式……',
      complete: '这就是你介绍我的方式。谢谢你认真选了它！',
    },
    logicSteps: [
      { icon: '🦘', label: 'Hop 先', order: '活力' },
      { icon: '💬', label: 'Say 先', order: '礼貌' },
    ],
    logicWhy: '两种顺序都不改变原著结果——石猴都来到花果山想认识伙伴；顺序改变的是观众先看见他的哪一种性格。',
    completionTitle: 'Build 2 完成！🎭',
    completion: '你运行并比较了两种真诚的问候，用故事理由保存了属于你的那一版。',
    completionSteps: [
      { icon: '🎭', label: '两版比较', order: '先' },
      { icon: '💾', label: '留下你的选择', order: '后' },
    ],
    completionWhy: '同样的四块动作，不同的顺序讲出不同的性格——这就是顺序的表达力。',
    next: '正当大家准备互相介绍，舞台忽然放出一个声音先出现、动作看不见的乱序版本。下一个 Part：找出第一个奇怪的地方。',
  },

  // Journey to the West S1/C1-P6 — Twist & Debug: the stable order bug. The
  // starter ships Say → Hop → Show; the child must RUN the bug first, find the
  // first deviation, then move ONLY the target blocks and rerun (manual-fix:
  // the repair is a real drag reorder, no picker or auto-answer exists).
  'jtw-s1-c1-p6': {
    mode: 'manual-fix',
    lessonId: 'jtw-s1-c1-p6',
    hero: {
      name: '石猴',
      role: '花果山的新朋友',
      asset: '/story-blocks/journey-to-the-west/characters/stone-monkey/neutral-v01.png',
    },
    eyebrow: '西游记 · 第一章 · Debug',
    title: '声音怎么从空中来了',
    storyPages: [
      {
        emoji: '💬❓',
        title: '声音先响了，石台却空空的',
        body: '舞台重新开始，大家先听见一句“你好”，可石台上空空的。草叶摇了一下，像有什么看不见的角色跳过；直到最后，石猴才突然出现。',
        speaker: '群猴',
        dialogue: '刚才是谁在说话？谁在跳？',
        scene: 1,
      },
      {
        emoji: '🧩⏱️',
        title: '每一块都能跑，顺序却把因果拆散了',
        body: '这不是石猴想讲的出世故事。他没有把积木推倒重来，而是请你先说预期，再按 Go 完整看一遍这个 bug——找到第一个看不懂的动作。',
        speaker: '石猴',
        dialogue: '大家应该什么时候看见我？先运行，再沿轨迹找第一个偏离。',
        scene: 3,
        blocks: ['💬 Say → 🦘 Hop → 👀 Show', '这是 bug 的顺序'],
      },
      {
        emoji: '👀🦘💬',
        title: '只移动目标块，再跑一遍',
        body: 'Say 发生时，Show 还没有发生——所以声音像从空中来。只把 Show、Hop、Say 三块移成先出现、再动作、后问候，不删积木、不换声音，重跑比较。',
        speaker: '石猴',
        dialogue: '让我先出现，跳和问好就都被看懂了。',
        scene: 4,
        blocks: ['👀 Show → 🦘 Hop → 💬 Say', '这是修好的顺序'],
      },
    ],
    partnerLine: '先跑 bug，再修顺序——只移动 Show、Hop、Say 三块，其他什么都不要动。',
    mission:
      '先按 Go 运行这条乱序链，听声音怎么从空中来；然后只移动 Show、Hop 和 Say 三块，让顺序变成 Show → Hop → Say，再按 Go 重跑比较。不许删掉重搭，也不许改声音。',
    question: '第一个观众看不懂的动作在哪里？',
    choices: [],
    retry: '还没修好——只移动 Show、Hop、Say 三块，让顺序变成先出现、再动作、后问候，再按 Go 重跑。',
    successTitle: '顺序修好了！⭐',
    success: '你先复现了 bug，又只移动目标块把因果接回去——这次每一步都被看懂了。',
    fixTitle: '把顺序修回来',
    fixPrompt: '关掉这张卡，先按 Go 跑一遍 bug，再把 Show 移到 Hop 和 Say 之前。',
    workspaceIntro: '乱序的亮相在等你：先运行 bug，再只移动目标块。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先按 Go 完整看一遍这个 bug——先别急着修。',
      watch: '听：声音是从空中来的吗？石台上有人吗？',
      sayFirst: '问候先响了，可我还没出现——这就是第一个偏离。',
      sayThen: '问候排在出现之后了，大家听得清清楚楚。',
      hopFirst: '草叶动了，可没人看见是谁在跳。',
      hopThen: '现在大家先看见我，再看见我跳。',
      retry: '还没修好。只移动 Show、Hop、Say 三块，别删、别换声音。',
      fix: '把 Show 移到 Hop 和 Say 之前——只动这三块。',
      test: '顺序改好了。按 Go 重跑，和刚才的 bug 比一比！',
      saving: '这一版每一步都看得懂。我在保存你的修复……',
      complete: '你修好了乱序的亮相——不是山风在说话，是我在按顺序介绍自己！',
    },
    logicSteps: [
      { icon: '▶️', label: '先跑 bug', order: '复现' },
      { icon: '🔍', label: '找第一次偏离', order: '定位' },
      { icon: '👀', label: 'Show 移到最前', order: '修复' },
    ],
    logicWhy: '积木从左到右运行：Say 排在 Show 前面时，声音就发生在没人可看的舞台上；只把目标块移回去，因果就接上了。',
    completionTitle: 'Debug 完成！🔧',
    completion: '你运行并复现了 bug，找到第一次偏离，只移动目标块修好顺序，并重跑验证了结果。',
    completionSteps: [
      { icon: '💬', label: '空中的声音', order: '复现' },
      { icon: '🔍', label: 'Say 在 Show 前', order: '定位' },
      { icon: '✅', label: '先看见再听清', order: '修复' },
    ],
    completionWhy: '重跑时群猴先看见石猴，再看见他跳，最后听清问候——每个可见变化都回到了正确的位置。',
    next: '一只群猴从树后走出来回应。下一个 Part：把这次亮相设计成你自己的版本。',
  },

  // Journey to the West S1/C1-P7 — the Personal Ship: the child designs their
  // own arrival. The frame (Start·hide·sound·Show … Say(preset)·End) ships;
  // the sound choice, the two visible actions (order + optional wait between)
  // and the preset greeting are the child's real decisions.
  'jtw-s1-c1-p7': {
    mode: 'personal-ship',
    lessonId: 'jtw-s1-c1-p7',
    hero: {
      name: '石猴',
      role: '花果山的新朋友',
      asset: '/story-blocks/journey-to-the-west/characters/stone-monkey/neutral-v01.png',
    },
    eyebrow: '西游记 · 第一章 · Personal Ship',
    title: '我的石猴亮相',
    storyPages: [
      {
        emoji: '🐒🎭',
        title: '石台中央留给新伙伴',
        body: '群猴围成一个宽宽的半圆，把石台中央留给石猴。他已经学会让故事清楚发生，现在他想让这次亮相也带一点自己的性格。',
        speaker: '石猴',
        dialogue: '这一次的亮相，由你来替我设计！',
        scene: 1,
      },
      {
        emoji: '🦘⏱️🔼',
        title: '两个动作、一个节奏、一句问候',
        body: '在 Show 和问候之间接上两个能被看见的动作——跳、转身、变大、变小都可以；中间还可以停一停（Wait 1–3），让观众看清节奏。声音和问候也由你选。',
        speaker: '石猴',
        dialogue: '等待不是拖时间，是让伙伴看清我的节奏。',
        scene: 3,
        blocks: ['👀 Show → 动作1 (→ ⏱ Wait) → 动作2', '💬 Say(预设问候) → 🏁 End'],
      },
      {
        emoji: '💾🔁',
        title: '保存、关闭、重开、再跑一遍',
        body: '完成后先从头预测，运行给同伴看；然后保存并关闭作品，再重新打开、重跑一遍——石猴仍按同样顺序亮相，你的第一次故事才不会丢。',
        speaker: '群猴',
        dialogue: '我们只看舞台，不看积木——讲给我们听！',
        scene: 4,
      },
    ],
    partnerLine: '出世链学会了，这一次的亮相由你设计——每个选择都要说得出理由。',
    mission:
      'Start、hide、声音、Show、一句预设问候和 End 已经放好。把两个可见动作（跳/转身/变大/变小）按你的顺序接到 Show 和问候之间，中间可以加一个 Wait 1–3；声音和问候也可以换成你喜欢的。运行、保存，然后关闭重开再跑一遍。',
    question: '同伴只看舞台，应该看出什么顺序？',
    choices: [],
    retry: '两个动作都要真的被看见——接在 Show 之后、问候之前，再按 Go 试试。',
    successTitle: '这是你自己的亮相！⭐',
    success: '两个动作、节奏和问候都是你选的。保存好，关闭重开它也不会丢。',
    fixTitle: '把你的亮相搭完整',
    fixPrompt: '关掉这张卡，把两个可见动作接到 Show 和问候之间，按你的顺序排好。',
    workspaceIntro: '石台中央空着，等你把自己设计的亮相搭出来。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '把两个可见动作按你的顺序接到 Show 和问候之间；想要节奏就加一个 Wait。',
      watch: '看你的设计从左到右运行——每一步都被看见了吗？',
      sayFirst: '问候说出口了——这是你为石猴写下的话。',
      sayThen: '问候排在动作之后，大家先看见你的性格，再听见你的话。',
      hopFirst: '第一个动作亮相了——伙伴正在看你的性格表达！',
      hopThen: '第二个动作接上了——两个动作让故事更完整。',
      retry: '还差一点。两个动作都要接在 Show 之后、问候之前，以 End 收尾。',
      fix: '在真正的工作区里搭你自己的版本——没有按钮会替你设计。',
      test: '你的亮相搭好了。按 Go 看看效果！',
      saving: '我在保存你设计的亮相……',
      complete: '这就是我的亮相——是你替我设计的！记得关闭重开再跑一遍。',
    },
    logicSteps: [
      { icon: '🔔', label: '选声音', order: '提示' },
      { icon: '🦘', label: '两个动作', order: '性格' },
      { icon: '💬', label: '预设问候', order: '联系' },
    ],
    logicWhy: '同样的顺序骨架，不同的动作、节奏和对白，讲出属于你的石猴——顺序讲清故事，选择表达性格。',
    completionTitle: 'Personal Ship 完成！🎉',
    completion: '你主导了声音、两个可见动作、顺序、节奏和问候，至少做出五个有意义的选择，并保存、重开、重跑验证了作品。',
    completionSteps: [
      { icon: '🎨', label: '自己的设计', order: '先' },
      { icon: '💾', label: '保存重开', order: '再' },
      { icon: '🗣️', label: '同伴复述', order: '最后' },
    ],
    completionWhy: '同伴不看积木也能复述出主要顺序，说明你的程序把故事讲清楚了——这就是作品完成的证据。',
    next: '清泉旁传来持续的轰鸣，湿润的风从山谷吹来。下一个 Part：跟着水声走。',
  },

  // Journey to the West S1/C2-P4 — chapter two's main Build. The starter ships
  // only Start/End; the child selects and orders the five one-step route
  // blocks (Right 1 ×2 · Up 1 · Right 1 ×2) with Left/Down/Wait as live
  // distractors — the parameter-merged 右2/上1/右2 shortcut never completes.,
};
