import type { StoryMission } from './types'
import {
  JTW_C4_P4_LESSON_ID,
  JTW_C4_P5_LESSON_ID,
  JTW_C4_P6_LESSON_ID,
  JTW_C4_WUKONG_ASSET,
} from '../jtwC4DualBuild'

export const JTW_C4_MISSIONS: Record<string, StoryMission> = {
  [JTW_C4_P4_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P4_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '先介绍、再回应的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Build 1',
    title: '名字先站稳，本领再回应',
    storyPages: [
      {
        emoji: '🏷️🐒',
        title: '伙伴要先记住名字',
        body: '师父给石猴取姓“孙”，又给他法名“悟空”。从现在起，伙伴和观众都能用同一个名字认识他；过去的花果山旅程并没有被换掉。',
        speaker: '师父',
        dialogue: '从今天起，你有一个名字——孙悟空。',
        scene: 1,
      },
      {
        emoji: '🚩👆',
        title: '两种开始在等不同的条件',
        body: 'Start等待场景开始，负责名字牌和自我介绍；Tap等待观众邀请，才让悟空展示一个小本领。两条链的动作不能混在一起。',
        scene: 3,
        blocks: ['🚩 Start → Show → Say → End', '👆 Tap → Hop 2 → Say → End'],
      },
      {
        emoji: '🧪🍃',
        title: '先Go等一等，再真实Tap',
        body: '先按Go，确认名字牌稳定亮起而叶纹目标保持安静；然后点舞台上的悟空，确认Hop和邀请对白才出现。两条轨迹都要走到End。',
        scene: 4,
      },
    ],
    partnerLine: '六块都由你放进正确的入口链；没有按钮会替你搭好。',
    mission: '在两个固定Trigger后放置六块：Start链放Show、名字Say和End；Tap链放Hop 2、邀请Say和End。先Go等一等，再点悟空。',
    question: '只按Go时，哪条链必须保持安静？',
    choices: [],
    retry: '检查每块在等哪个入口：名字跟Start，本领跟Tap；两条链都要有End。',
    successTitle: '两个入口都说清楚了',
    success: '名字牌先稳定出现；收到邀请后，叶纹目标才随着小展示亮起。',
    fixTitle: '把六块分回正确入口',
    fixPrompt: 'Start → Show → 名字Say → End；Tap → Hop 2 → 邀请Say → End。',
    workspaceIntro: '两个Trigger已经固定，六个任务槽等你补齐。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先搭两条链，再做Go和Tap双测试。',
      watch: '只按Go时，本领链保持安静吗？',
      sayFirst: '名字先出现。',
      sayThen: '邀请后再回应。',
      hopFirst: 'Hop属于Tap链。',
      hopThen: '叶纹目标只在Tap后亮。',
      retry: '有块放错入口、缺少End，或还没完成双测试。',
      fix: '把名字块放回Start，把本领块放回Tap。',
      test: '先Go并等待，再点悟空。',
      saving: '两条真实轨迹都完成了，正在保存。',
      complete: '伙伴先记住名字，收到邀请后才看见小展示。',
    },
    logicSteps: [
      { icon: '🚩', label: '名字链', order: '先Go' },
      { icon: '⏸️', label: '本领安静', order: '等待' },
      { icon: '👆', label: '本领链', order: '再Tap' },
    ],
    logicWhy: 'Trigger决定脚本等待的条件；同一动作放在不同入口后，会在不同时间发生。',
    completionTitle: 'Build 1完成',
    completion: '六块真实积木归属正确，Go和Tap两次真实运行都稳定到End。',
    completionSteps: [
      { icon: '🏷️', label: '名字站稳', order: '先' },
      { icon: '🍃', label: '邀请回应', order: '后' },
    ],
    completionWhy: '不点悟空时本领没有偷跑，说明两条事件链真的分开了。',
    next: '伙伴记住了名字。下一Part由孩子选择悟空回应邀请的小展示。',
  },
  [JTW_C4_P5_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P5_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '等到邀请再回应的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · 故事选择',
    title: '本领不是为了抢先',
    storyPages: [{
      emoji: '👆🐒',
      title: '邀请到了，才开始回应',
      body: '保留名字链，在Tap入口后搭好你选的动作、等待和对白。',
      scene: 5,
    }],
    partnerLine: '同伴先读程序，预测Tap后会看到什么。',
    mission: '保留名字链；亲手搭好所选Tap链。先Go确认安静，再Tap悟空。',
    question: '为什么展示要等Tap？',
    choices: [],
    retry: '名字链不能删除；展示必须完整留在Tap入口后。',
    successTitle: '回应等到了邀请',
    success: 'Go只显示名字；Tap后才出现选择的展示。',
    fixTitle: '把展示留在Tap链',
    fixPrompt: '检查动作顺序、对白和End。',
    workspaceIntro: '名字链保留，Tap链等你搭出所选版本。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先搭选择版本，再做Go和Tap双测试。',
      watch: 'Go后展示链保持安静吗？',
      sayFirst: '先让同伴预测。',
      sayThen: '再Tap验证。',
      hopFirst: '动作属于Tap链。',
      hopThen: '等待让变化看得清。',
      retry: '版本未完整或双测试尚未完成。',
      fix: '保留名字链，把展示接在Tap后。',
      test: '先Go等待，再真实Tap悟空。',
      saving: '选择和双运行证据正在保存。',
      complete: '悟空在观众准备好后才回应。',
    },
    logicSteps: [
      { icon: '🧠', label: '同伴预测', order: '先' },
      { icon: '🚩', label: '名字站稳', order: '再' },
      { icon: '👆', label: '邀请回应', order: '后' },
    ],
    logicWhy: '真实选择改变Tap链的动作、顺序和可见结果。',
    completionTitle: '故事选择完成',
    completion: '所选版本已保存，Go和Tap两次真实运行都完成。',
    completionSteps: [
      { icon: '🏷️', label: '名字保留', order: '先' },
      { icon: '✨', label: '展示回应', order: '后' },
    ],
    completionWhy: '展示没有抢跑，说明孩子理解动作为什么等待邀请。',
    next: '一阵风把整段本领链吹错入口；下一Part检查第一次偏离。',
  },
  [JTW_C4_P6_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P6_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '先找第一次偏离的排错者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Debug',
    title: '先找第一次偏离',
    storyPages: [{
      emoji: '🚩↔️👆',
      title: '动作没变，等待的入口变了',
      body: '先Go复现名字和本领连续自动发生；保留全部动作，只把本领小链的Trigger从Start改成Tap。',
      scene: 5,
    }],
    partnerLine: '同伴先说预期，再看错误run第一次从哪里偏离。',
    mission: '先运行错误版；只改本领链Trigger；再Go等待并真实Tap悟空。',
    question: '第一次偏离在哪里？',
    choices: [],
    retry: '不能删动作、改参数或跳过错误run；唯一diff是Start变成Tap。',
    successTitle: '两条事件路重新分开',
    success: '名字先出现并等待；Tap后完整展示原来的动作组。',
    fixTitle: '只修入口归属',
    fixPrompt: '点击本领链第一个Start，把它改成Tap。',
    workspaceIntro: '动作组完整保留，但错误地等着Start。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先按Go复现抢跑，再触碰Trigger。',
      watch: '名字后面，本领是不是没有等邀请？',
      sayFirst: '先说正确预期。',
      sayThen: '再指出第一次偏离。',
      hopFirst: '动作组必须保持不变。',
      hopThen: 'Tap后才完整回应。',
      retry: '需要错误run、单一Trigger diff、Go等待和真实Tap。',
      fix: '只把本领链Start改成Tap。',
      test: '先Go等待，再真实Tap悟空。',
      saving: '错误和修复后的双事件证据正在保存。',
      complete: '悟空先得名，再等邀请展示。',
    },
    logicSteps: [
      { icon: '🧠', label: '说出预期', order: '先' },
      { icon: '🚩', label: '复现抢跑', order: '再' },
      { icon: '👆', label: '修复并Tap', order: '后' },
    ],
    logicWhy: 'Trigger决定动作在等待Go还是等待角色Tap。',
    completionTitle: 'Debug完成',
    completion: '错误run和修复后的Go等待、Tap展示都已真实运行并保存。',
    completionSteps: [
      { icon: '🏷️', label: '名字先出现', order: '先' },
      { icon: '✨', label: '邀请后展示', order: '后' },
    ],
    completionWhy: '动作内容完全不变，只有入口归属改变。',
    next: '下一Part把名字与本领做成可保存、可供同伴发现的个人版本。',
  },
}
