import { JTW_C5_P4_LESSON_ID, JTW_C5_P5_LESSON_ID } from '../jtwC5SizeBuild'
import { JTW_C4_WUKONG_ASSET } from '../jtwC4DualBuild'
import type { StoryMission } from './types'

const coach = {
  ready: '先预测三个大小停点，再搭或调整状态链。',
  watch: '每个状态变化都来自真实运行器。',
  sayFirst: '先读环境与用途。',
  sayThen: '再运行检查结尾。',
  hopFirst: 'Grow、Reset、Shrink各有不同状态作用。',
  hopThen: 'Wait只帮助观众看清。',
  retry: '检查完整AST、状态顺序、参数和End。',
  fix: '只改任务要求的状态、Wait或预设Say。',
  test: '按Go，从Start运行到End。',
  saving: '真实大小轨迹正在保存。',
  complete: '最终小状态让窄门保持打开。',
} as const

export const JTW_C5_MISSIONS: Record<string, StoryMission> = {
  [JTW_C5_P4_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C5_P4_LESSON_ID,
    celebrate: false,
    allowedOps: ['grow', 'reset_size', 'shrink', 'wait', 'turn_right'],
    hero: { name: '悟空', role: '比较大小状态的搭建者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第五章 · Build',
    title: '搭出完整大小试验',
    storyPages: [{ emoji: '🟨↕️', title: '四个任务块都由你放', body: '在Start和End之间放Grow 2、Wait 5、Reset和Shrink 2；Turn Right是会被完整AST拒绝的干扰块。', scene: 4 }],
    partnerLine: '伙伴先看三张状态卡，再观察真实轨迹。',
    mission: '放置四块并排序，按Go运行到End。',
    question: '最后哪个状态适合通过窄门？',
    choices: [],
    retry: '缺块、参数不对、含干扰块或顺序不对都不能完成。',
    successTitle: '三个大小停点都看清了',
    success: '金箍棒最后停在可携带的小状态。',
    fixTitle: '检查四个任务块',
    fixPrompt: 'Grow 2 → Wait 5 → Reset → Shrink 2。',
    workspaceIntro: 'Start和End已固定，四个任务块等你放入。',
    fixChoices: [],
    fixRetry: '',
    coach,
    logicSteps: [{ icon: '🔼', label: '变大', order: '先' }, { icon: '🔄', label: '复原', order: '再' }, { icon: '🔽', label: '携带', order: '后' }],
    logicWhy: '状态块会改变当前大小，最后的状态块决定End时留下什么。',
    completionTitle: '大小试验完成',
    completion: '四块真实编辑和完整大小轨迹都已保存。',
    completionSteps: [{ icon: '🧩', label: '四块', order: '搭' }, { icon: '▶️', label: '轨迹', order: '跑' }],
    completionWhy: '干扰块没有进入成功AST，三个大小状态来自解释器。',
    next: '回到Part页面选择三段用途。',
  },
  [JTW_C5_P5_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C5_P5_LESSON_ID,
    celebrate: false,
    allowedOps: ['grow', 'reset_size', 'shrink', 'wait', 'say'],
    hero: { name: '悟空', role: '按环境选择合适结尾的设计者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第五章 · Meaningful Choice',
    title: '最大不等于最合适',
    storyPages: [{ emoji: '🚪〰️', title: '从自己的P4链继续', body: '改变状态顺序或Wait节奏，加入一条预设用途Say；最后的状态必须仍适合携带。', scene: 5 }],
    partnerLine: '伙伴从三个停点和用途标签读你的选择。',
    mission: '保留三次状态变化，改变顺序或节奏，加入预设Say，并让Shrink成为最后的状态变化。',
    question: '为什么最大状态不能留在结尾？',
    choices: [],
    retry: '需要三次状态变化、Wait、预设Say、End和可携带结尾。',
    successTitle: '安全线亮起来了',
    success: '用途标签来自真实链，最终小状态通过窄门。',
    fixTitle: '让用途和环境限制对齐',
    fixPrompt: '可以改变状态顺序或Wait节奏，但最后一次状态变化必须是Shrink。',
    workspaceIntro: 'P4保存链已载入；现在作一次真实逻辑选择。',
    fixChoices: [],
    fixRetry: '',
    coach,
    logicSteps: [{ icon: '👀', label: '原貌', order: '一' }, { icon: '⚖️', label: '比较', order: '二' }, { icon: '🎒', label: '携带', order: '三' }],
    logicWhy: '同样的状态块换顺序会改变结尾，环境限制决定哪个结尾合适。',
    completionTitle: '用途选择完成',
    completion: 'before/after AST、用途Say、真实轨迹与安全结尾都已保存。',
    completionSteps: [{ icon: '🧠', label: '选择', order: '先' }, { icon: '▶️', label: '验证', order: '后' }],
    completionWhy: '不是装饰变化，而是状态顺序、节奏或表达改变。',
    next: '下一Part检查末尾站错位置的Reset。',
  },
}
