import type { StoryMission } from './types'
import {
  JTW_C4_P4_LESSON_ID,
  JTW_C4_P5_LESSON_ID,
  JTW_C4_P6_LESSON_ID,
  JTW_C4_P7_LESSON_ID,
  JTW_C4_WUKONG_ASSET,
} from '../jtwC4DualBuild'

export const JTW_C4_MISSIONS: Record<string, StoryMission> = {
  [JTW_C4_P7_LESSON_ID]: {
    mode: 'personal-ship', lessonId: JTW_C4_P7_LESSON_ID, celebrate: false,
    hero: { name: '孙悟空', role: '等待同伴发现邀请入口的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Personal Ship', title: 'Meet Sun Wukong',
    storyPages: [{ emoji: '🏷️👆', title: '让同伴真正认识悟空', body: '名字由Start出现；轻微指尖线索帮助同伴发现悟空可点，本领仍只在真实Tap后回应。', scene: 5 }],
    partnerLine: '同伴没有口头答案：先Go，再自己找到悟空并Tap。',
    mission: '保留两条独立脚本，完成Go与真实Tap，保存后关闭重开。',
    question: '怎样让同伴发现邀请入口？', choices: [], retry: '不能把Tap链改成自动播放。',
    successTitle: '同伴找到了邀请入口', success: '名字牌和所选目标都保存在个人作品中。',
    fixTitle: '制作个人认识卡', fixPrompt: '保持Go得名、Tap展示，并完成两条End。', workspaceIntro: '三个版本都是真实选择；作品名固定为Meet Sun Wukong。', fixChoices: [], fixRetry: '',
    coach: { ready: '先预测两条事件。', watch: 'Go后本领保持安静吗？', sayFirst: '名字先出现。', sayThen: 'Tap后才说。', hopFirst: '动作属于邀请入口。', hopThen: '同伴自己发现可点对象。', retry: '检查两条脚本、双运行与End。', fix: '只修可发现性，不改Trigger。', test: '先Go，再让同伴Tap悟空。', saving: '真实双事件结果正在保存。', complete: '个人认识卡可以重开再运行。' },
    logicSteps: [{ icon: '🚩', label: '得名', order: 'Go' }, { icon: '👆', label: '展示', order: 'Tap' }], logicWhy: '同一角色用两个Trigger等待不同条件。',
    completionTitle: 'Personal Ship已运行', completion: '双事件结果已写入保存版本。', completionSteps: [{ icon: '💾', label: '保存', order: '先' }, { icon: '🔁', label: '重开复测', order: '后' }], completionWhy: '页面还会核对关闭、重开与JSON一致。', next: '最后讲回远行、得名、学习与等待邀请。',
  },
  [JTW_C4_P6_LESSON_ID]: {
    mode: 'observe-fix',
    lessonId: JTW_C4_P6_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '把本领放回正确入口的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Debug',
    title: '先找第一次偏离',
    storyPages: [{ emoji: '🌬️🚩', title: '本领排错队', body: '风把完整本领链吹到Start入口。先说预期，再运行错误版，找到第一次偏离。', scene: 5 }],
    partnerLine: '只改Trigger归属，动作、参数、顺序、名字链和背景都保持不变。',
    mission: '把完整本领小链从Start重接到Tap；先Go等待，再真实Tap悟空。',
    question: '这条本领脚本在等什么？',
    choices: [{ id: 'tap', label: '等观众Tap悟空', correct: true }, { id: 'flag', label: '等Go开始', correct: false }],
    retry: '第一次偏离是本领用了Start，不是动作参数。',
    successTitle: '两条路重新分开',
    success: '名字先出现；悟空等邀请后才完整展示。',
    fixTitle: '只修Trigger归属',
    fixPrompt: '保留整组动作，只把本领链入口从Start换成Tap。',
    workspaceIntro: '错误版会在Go后自动展示；先运行看见错误，再重接Trigger。',
    fixChoices: [],
    fixRetry: '删除动作或改参数都不是这次修复。',
    coach: { ready: '先运行错误版。', watch: '名字后为什么立刻展示？', sayFirst: '名字属于Start。', sayThen: '对白保持原样。', hopFirst: '动作组没有错。', hopThen: '它应等Tap。', retry: '动作组内容或Trigger仍不对。', fix: '逐块重接到Tap入口。', test: '先Go等待，再Tap悟空。', saving: '双运行证据已量到。', complete: '本领不再抢先。' },
    logicSteps: [{ icon: '🚩', label: '名字', order: 'Go' }, { icon: '👆', label: '本领', order: 'Tap' }],
    logicWhy: 'Trigger决定整条脚本在等什么。',
    completionTitle: 'Debug完成',
    completion: '错误run、单一Trigger修复、Go等待与真实Tap都已保存。',
    completionSteps: [{ icon: '🏷️', label: '先得名', order: '先' }, { icon: '✨', label: '再展示', order: '后' }],
    completionWhy: '动作没有被删除或改写，只换回正确入口。',
    next: '下一步制作可保存、可供同伴发现的个人认识卡。',
  },
  [JTW_C4_P4_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P4_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '先介绍、再回应的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Build 1',
    title: '名字先站稳，本领再回应',
    storyPages: [
      {
        emoji: '🏷️🐒',
        title: '伙伴要先记住名字',
        body: '师父给石猴取姓“孙”，又给他法名“悟空”。从现在起，伙伴和观众都能用同一个名字认识他；过去的花果山旅程并没有被换掉。',
        speaker: '师父',
        dialogue: '从今天起，你有一个名字——孙悟空。',
        scene: 1,
      },
      {
        emoji: '🚩👆',
        title: '两种开始在等不同的条件',
        body: 'Start等待场景开始，负责名字牌和自我介绍；Tap等待观众邀请，才让悟空展示一个小本领。两条链的动作不能混在一起。',
        scene: 3,
        blocks: ['🚩 Start → Show → Say → End', '👆 Tap → Hop 2 → Say → End'],
      },
      {
        emoji: '🧪🍃',
        title: '先Go等一等，再真实Tap',
        body: '先按Go，确认名字牌稳定亮起而叶纹目标保持安静；然后点舞台上的悟空，确认Hop和邀请对白才出现。两条轨迹都要走到End。',
        scene: 4,
      },
    ],
    partnerLine: '六块都由你放进正确的入口链；没有按钮会替你搭好。',
    mission: '在两个固定Trigger后放置六块：Start链放Show、名字Say和End；Tap链放Hop 2、邀请Say和End。先Go等一等，再点悟空。',
    question: '只按Go时，哪条链必须保持安静？',
    choices: [],
    retry: '检查每块在等哪个入口：名字跟Start，本领跟Tap；两条链都要有End。',
    successTitle: '两个入口都说清楚了',
    success: '名字牌先稳定出现；收到邀请后，叶纹目标才随着小展示亮起。',
    fixTitle: '把六块分回正确入口',
    fixPrompt: 'Start → Show → 名字Say → End；Tap → Hop 2 → 邀请Say → End。',
    workspaceIntro: '两个Trigger已经固定，六个任务槽等你补齐。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先搭两条链，再做Go和Tap双测试。',
      watch: '只按Go时，本领链保持安静吗？',
      sayFirst: '名字先出现。',
      sayThen: '邀请后再回应。',
      hopFirst: 'Hop属于Tap链。',
      hopThen: '叶纹目标只在Tap后亮。',
      retry: '有块放错入口、缺少End，或还没完成双测试。',
      fix: '把名字块放回Start，把本领块放回Tap。',
      test: '先Go并等待，再点悟空。',
      saving: '两条真实轨迹都完成了，正在保存。',
      complete: '伙伴先记住名字，收到邀请后才看见小展示。',
    },
    logicSteps: [
      { icon: '🚩', label: '名字链', order: '先Go' },
      { icon: '⏸️', label: '本领安静', order: '等待' },
      { icon: '👆', label: '本领链', order: '再Tap' },
    ],
    logicWhy: 'Trigger决定脚本等待的条件；同一动作放在不同入口后，会在不同时间发生。',
    completionTitle: 'Build 1完成',
    completion: '六块真实积木归属正确，Go和Tap两次真实运行都稳定到End。',
    completionSteps: [
      { icon: '🏷️', label: '名字站稳', order: '先' },
      { icon: '🍃', label: '邀请回应', order: '后' },
    ],
    completionWhy: '不点悟空时本领没有偷跑，说明两条事件链真的分开了。',
    next: '伙伴记住了名字。下一Part由孩子选择悟空回应邀请的小展示。',
  },
  [JTW_C4_P5_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P5_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '等到邀请再回应的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Expression Choice',
    title: '本领不是为了抢先',
    storyPages: [
      { emoji: '👆🐒', title: '先等观众准备好', body: '名字链保持不变；Tap链由你选择一种温和回应。', scene: 5 },
      { emoji: '🧩', title: '三种真实版本', body: '跃过叶纹、转身指家或屏风再现。选择会改变动作、顺序和可见结果。', scene: 5 },
      { emoji: '🚩👆', title: '双测试', body: '先Go确认名字，再请同伴预测并真实Tap悟空。', scene: 5 },
    ],
    partnerLine: '同伴先预测，再点舞台上的悟空验证。',
    mission: '保留名字链，在Tap入口后搭出你选择的完整回应链，再完成Go与真实Tap双测试。',
    question: '为什么本领链要等Tap？',
    choices: [],
    retry: '名字链不能删除；Tap链必须完整匹配一种有效版本并到End。',
    successTitle: '悟空等到邀请才回应',
    success: '所选动作只在真实Tap后出现，名字仍由Start控制。',
    fixTitle: '搭好所选回应链',
    fixPrompt: '把所选动作、等待或对白按顺序接在On Tap后。',
    workspaceIntro: '名字链已经保留，Tap链等待你的真实选择。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先选版本并搭好，再做双测试。', watch: 'Go后本领保持安静吗？',
      sayFirst: '名字先出现。', sayThen: '邀请后才回应。', hopFirst: '动作属于Tap链。',
      hopThen: '可见目标只在Tap后改变。', retry: '检查版本顺序和End。',
      fix: '保留名字链，修好Tap链。', test: '先Go，再真实Tap。',
      saving: '选择与两次轨迹正在保存。', complete: '悟空等到观众准备好才回应。',
    },
    logicSteps: [
      { icon: '🚩', label: '名字', order: '先Go' },
      { icon: '💭', label: '同伴预测', order: '再说' },
      { icon: '👆', label: '所选回应', order: '后Tap' },
    ],
    logicWhy: '真实选择改变Tap链，但不会改变它等待邀请的条件。',
    completionTitle: 'Expression Choice完成',
    completion: '一种有效版本已保存，并通过Go与真实Tap验证。',
    completionSteps: [{ icon: '🏷️', label: '名字保留', order: '先' }, { icon: '✨', label: '选择回应', order: '后' }],
    completionWhy: '本领没有自动播放，说明选择和事件条件都真实生效。',
    next: '一阵风把整段本领链吹到错误入口；下一Part检查第一次偏离。',
  },
}
