import type { StoryMission } from './types'
import { JTW_C4_P4_LESSON_ID, JTW_C4_WUKONG_ASSET } from '../jtwC4DualBuild'

export const JTW_C4_MISSIONS: Record<string, StoryMission> = {
  [JTW_C4_P4_LESSON_ID]: {
    mode: 'complete',
    lessonId: JTW_C4_P4_LESSON_ID,
    celebrate: false,
    hero: { name: '孙悟空', role: '先介绍、再回应的学习者', asset: JTW_C4_WUKONG_ASSET },
    eyebrow: '西游记 · 第四章 · Build 1',
    title: '名字先站稳，本领再回应',
    storyPages: [
      {
        emoji: '🏷️🐒',
        title: '伙伴要先记住名字',
        body: '师父给石猴取姓“孙”，又给他法名“悟空”。从现在起，伙伴和观众都能用同一个名字认识他；过去的花果山旅程并没有被换掉。',
        speaker: '师父',
        dialogue: '从今天起，你有一个名字——孙悟空。',
        scene: 1,
      },
      {
        emoji: '🚩👆',
        title: '两种开始在等不同的条件',
        body: 'Start等待场景开始，负责名字牌和自我介绍；Tap等待观众邀请，才让悟空展示一个小本领。两条链的动作不能混在一起。',
        scene: 3,
        blocks: ['🚩 Start → Show → Say → End', '👆 Tap → Hop 2 → Say → End'],
      },
      {
        emoji: '🧪🍃',
        title: '先Go等一等，再真实Tap',
        body: '先按Go，确认名字牌稳定亮起而叶纹目标保持安静；然后点舞台上的悟空，确认Hop和邀请对白才出现。两条轨迹都要走到End。',
        scene: 4,
      },
    ],
    partnerLine: '六块都由你放进正确的入口链；没有按钮会替你搭好。',
    mission: '在两个固定Trigger后放置六块：Start链放Show、名字Say和End；Tap链放Hop 2、邀请Say和End。先Go等一等，再点悟空。',
    question: '只按Go时，哪条链必须保持安静？',
    choices: [],
    retry: '检查每块在等哪个入口：名字跟Start，本领跟Tap；两条链都要有End。',
    successTitle: '两个入口都说清楚了',
    success: '名字牌先稳定出现；收到邀请后，叶纹目标才随着小展示亮起。',
    fixTitle: '把六块分回正确入口',
    fixPrompt: 'Start → Show → 名字Say → End；Tap → Hop 2 → 邀请Say → End。',
    workspaceIntro: '两个Trigger已经固定，六个任务槽等你补齐。',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: '先搭两条链，再做Go和Tap双测试。',
      watch: '只按Go时，本领链保持安静吗？',
      sayFirst: '名字先出现。',
      sayThen: '邀请后再回应。',
      hopFirst: 'Hop属于Tap链。',
      hopThen: '叶纹目标只在Tap后亮。',
      retry: '有块放错入口、缺少End，或还没完成双测试。',
      fix: '把名字块放回Start，把本领块放回Tap。',
      test: '先Go并等待，再点悟空。',
      saving: '两条真实轨迹都完成了，正在保存。',
      complete: '伙伴先记住名字，收到邀请后才看见小展示。',
    },
    logicSteps: [
      { icon: '🚩', label: '名字链', order: '先Go' },
      { icon: '⏸️', label: '本领安静', order: '等待' },
      { icon: '👆', label: '本领链', order: '再Tap' },
    ],
    logicWhy: 'Trigger决定脚本等待的条件；同一动作放在不同入口后，会在不同时间发生。',
    completionTitle: 'Build 1完成',
    completion: '六块真实积木归属正确，Go和Tap两次真实运行都稳定到End。',
    completionSteps: [
      { icon: '🏷️', label: '名字站稳', order: '先' },
      { icon: '🍃', label: '邀请回应', order: '后' },
    ],
    completionWhy: '不点悟空时本领没有偷跑，说明两条事件链真的分开了。',
    next: '伙伴记住了名字。下一Part由孩子选择悟空回应邀请的小展示。',
  },
}
