// Tiny Star Village A2｜团团走反了 — Story Blocks mission guides.
// Split out of curriculumGuides.ts to keep every file under the 1000-line
// hard rule in rules/file-organization.md. curriculumGuides.ts stays the
// public module and re-exports the assembled catalogue.

import type { StoryMission } from './types';

export const TSV_A2_MISSIONS: Record<string, StoryMission> = {
  'tsv-s1-a2-h': {
    mode: 'observe-only',
    lessonId: 'tsv-s1-a2-h',
    hero: {
      name: 'Tuan Tuan',
      role: 'Cloud-path Maker',
      asset: '/story-blocks/tiny-star-village/characters/cloud-bear/resting-happy-v01.png',
    },
    celebrate: false,
    eyebrow: 'Tiny Star Village · Chapter 2 · Mission 5',
    title: 'Press Go and watch',
    storyPages: [
      {
        emoji: '☁️🐻',
        title: 'First, press Go',
        body: 'Tuan Tuan wants to reach the glowing plaza star. His program already has one arrow block.',
        speaker: 'Tuan Tuan',
        dialogue: 'Can you watch where my arrow takes me?',
        visualSpeech: 'Where will I go?',
        scene: 1,
      },
      {
        emoji: '☁️⭐',
        title: 'The star is right. The block points left.',
        body: 'The plaza star is on Tuan Tuan’s right, but the blue block will move him left.',
        speaker: 'Tuan Tuan',
        dialogue: 'What will happen when the block moves me left?',
        visualSpeech: 'The block says Left!',
        scene: 2,
        direction: { arrow: 'left', target: 'Plaza star' },
      },
      {
        emoji: '👉▶️',
        title: 'Ready to test',
        body: 'The blue Left 3 block is already connected between Start and End.',
        speaker: 'Tuan Tuan',
        dialogue: 'I’m ready. Where will I stop?',
        visualSpeech: 'Ready!',
        scene: 3,
        direction: { arrow: 'left', target: 'Plaza star' },
        blocks: ['⬅️ Wrong: Left 3', '⭐ Plaza on right'],
      },
    ],
    partnerLine: 'Tuan Tuan is ready to try the program.',
    mission:
      'Press Go without changing the blocks. Then choose whether Tuan Tuan stopped closer to the star or farther away.',
    question: 'After moving left, is Tuan Tuan closer to the plaza star or farther away?',
    choices: [
      { id: 'closer', label: '⭐ Closer to the plaza', correct: false },
      { id: 'farther', label: '☁️ Farther from the plaza', correct: true },
    ],
    retry: 'Look at the gap between Tuan Tuan and the star. It grew wider.',
    successTitle: 'You read the path! ⭐',
    success: 'Tuan Tuan moved left while the plaza star stayed on the right, so the gap grew.',
    fixTitle: 'Story Hook complete',
    fixPrompt: 'Keep the Left block for now. You will choose a new arrow in the next mission.',
    workspaceIntro: 'Watching step only: the Left 3 block is wrong on purpose. Do not repair it or try to reach the star yet.',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: 'The star is on his right. Watch the gap.',
      watch: 'Watch the gap between me and the plaza star as I move left.',
      sayFirst: 'The plaza star stays on the right.',
      sayThen: 'The plaza star stays on the right.',
      hopFirst: 'I am moving left, away from the star.',
      hopThen: 'I am moving left, away from the star.',
      retry: 'Look again: the star is on the right and I move left.',
      fix: 'No fix yet. Tell me what happened to the gap.',
      test: 'Press Go again and watch where Tuan Tuan stops.',
      saving: 'No program change to save—this Hook checks what you observed.',
      complete: 'You saw the gap grow and correctly chose farther away!',
    },
    coachGoal: {
      label: 'Do this now',
      target: '▶ Press Go',
      now: 'Watch where Tuan Tuan stops.',
    },
    coachSteps: ['Story', 'Press Go', 'Watch him stop', 'Choose what happened'],
    coachGoLabel: 'Press Go',
    logicSteps: [
      { icon: '☁️', label: 'Tuan Tuan starts', order: 'Middle' },
      { icon: '⬅️', label: 'Moves 3 left', order: 'Then' },
      { icon: '⭐', label: 'Plaza stays right', order: 'Target' },
    ],
    logicWhy: 'Moving left while the target stays right makes the distance larger.',
    completionTitle: 'Story Hook complete · You spotted the wrong way!',
    completion:
      'You kept the starter scene unchanged, ran it to the end, and noticed that Tuan Tuan finished farther from the plaza star.',
    completionSteps: [
      { icon: '⭐', label: 'Point to target', order: 'Before Go' },
      { icon: '⬅️', label: 'Watch Left 3', order: 'Run' },
      { icon: '📏', label: 'Farther away', order: 'Observe' },
    ],
    completionWhy: 'Tuan Tuan moved from grid 8 to grid 5 while the plaza star stayed at grid 11.',
    next: 'Carry the Left and Right arrow cards into A2-B, where you will choose the arrow that reaches the plaza.',
  },
  'tsv-s1-a2-b': {
    mode: 'complete',
    lessonId: 'tsv-s1-a2-b',
    hero: {
      name: 'Tuan Tuan',
      role: 'Cloud-path Maker',
      asset: '/story-blocks/tiny-star-village/characters/cloud-bear/resting-happy-v01.png',
    },
    eyebrow: 'Tiny Star Village · Chapter 2 · Mission 6',
    title: 'Choose one arrow for the plaza',
    storyPages: [
      {
        emoji: '☁️🐻',
        title: 'Tuan Tuan remembers your careful watching',
        body: 'This is Tuan Tuan, the cloud-path maker you met on the glowing path. You watched the Left arrow carry Tuan Tuan farther from the plaza, and now Tuan Tuan is ready to follow your direction.',
        speaker: 'Tuan Tuan',
        dialogue: 'You saw where I went. Will you choose my next arrow?',
        visualSpeech: 'Thank you for watching my path!',
        scene: 1,
      },
      {
        emoji: '☁️➡️⭐',
        title: 'The plaza star is three steps right',
        body: 'Tuan Tuan starts in the middle at grid 8. The plaza star waits at grid 11. One three-step direction block can join Start to End and carry Tuan Tuan exactly to the star.',
        speaker: 'Tuan Tuan',
        dialogue: 'The star is on my right. Which arrow points toward it?',
        visualSpeech: 'My plaza star is over there!',
        scene: 2,
        direction: { arrow: 'right', target: 'Plaza star' },
      },
      {
        emoji: '🚩🧩🏁',
        title: 'Put one real arrow before End',
        body: 'Start and End are already connected. In the real workspace, open Motion and tap Left or Right. Your direction snaps before End with three steps ready. Press Go and see whether Tuan Tuan reaches the star.',
        speaker: 'Tuan Tuan',
        dialogue: 'Choose only one arrow. The path will show whether it points toward my star.',
        visualSpeech: 'One arrow, then Go!',
        scene: 4,
        blocks: ['🧩 Choose arrow', '🏁 End'],
      },
    ],
    partnerLine: 'You observed the wrong way. Now build the path that reaches the plaza!',
    mission:
      'Open Motion and add one direction block between Start and End. The block is already set to 3 steps. Press Go and help Tuan Tuan reach the plaza star on the right.',
    question: 'Which arrow points from Tuan Tuan toward the plaza star?',
    choices: [],
    retry: 'Look at the stage: the plaza star waits on the right.',
    successTitle: 'Your arrow is ready to test! ⭐',
    success: 'The real program now has one direction between Start and End.',
    fixTitle: 'Build the path in the real workspace',
    fixPrompt:
      'Close this card. Open Motion and tap one arrow. It will snap before End with 3 steps ready.',
    workspaceIntro:
      'No answer button can build this path. Add the real direction block between Start and End.',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: 'Open Motion and choose one arrow. The plaza star is on the right.',
      watch: 'Watch whether I finish on the plaza star at grid 11.',
      sayFirst: 'The plaza stays on the right.',
      sayThen: 'The plaza stays on the right.',
      hopFirst: 'I moved along your arrow.',
      hopThen: 'I moved along your arrow.',
      retry: 'That path did not reach the star. Keep one arrow between Start and End.',
      fix: 'Build with a real Motion block—there is no answer button.',
      test: 'Your Right 3 block points to the star. Press Go to test the path!',
      saving: 'Tuan Tuan reached grid 11. I am saving your real direction block…',
      complete: 'Your saved Right 3 path carried Tuan Tuan to the plaza star!',
    },
    coachGoal: {
      label: 'Goal',
      target: '⭐ Reach the plaza star on the RIGHT',
      now: 'Do this now: tap Motion → tap Right → press Go.',
    },
    coachSteps: ['Find ⭐ right', 'Tap Motion', 'Add Right 3', 'Press Go'],
    logicSteps: [
      { icon: '🚩', label: 'Start', order: 'Ready' },
      { icon: '🧩', label: 'Choose arrow', order: 'Build' },
      { icon: '🏁', label: 'End', order: 'Ready' },
    ],
    logicWhy: 'The empty space between Start and End needs one direction toward the target.',
    completionTitle: 'Mission 6 complete! ☁️⭐',
    completion:
      'You added a real Right 3 block, saved it, and ran the whole program. Tuan Tuan travelled from grid 8 to the plaza star at grid 11.',
    completionSteps: [
      { icon: '🚩', label: 'Start', order: 'First' },
      { icon: '➡️', label: 'Right 3', order: 'Then' },
      { icon: '🏁', label: 'End', order: 'Finish' },
    ],
    completionWhy: 'Right 3 adds three grid steps: 8 + 3 = 11, exactly where the plaza star waits.',
    next: 'Tuan Tuan arrives at the plaza. Next, a mixed-up arrow will test whether you can debug the same route.',
  },
  'tsv-s1-a2-d': {
    mode: 'manual-fix',
    lessonId: 'tsv-s1-a2-d',
    hero: {
      name: 'Tuan Tuan',
      role: 'Cloud-path Maker',
      asset: '/story-blocks/tiny-star-village/characters/cloud-bear/resting-happy-v01.png',
    },
    eyebrow: 'Tiny Star Village · Chapter 2 · Mission 7',
    title: 'Tuan Tuan walked the wrong way again',
    storyPages: [
      {
        emoji: '☁️🐻',
        title: 'Tuan Tuan has one mixed-up arrow',
        body: 'Tuan Tuan kept the three steps that reached the plaza. But a gust turned the arrow around. The plaza star is still on the right, while the path now points left.',
        speaker: 'Tuan Tuan',
        dialogue: 'My path has three steps, but is my arrow facing the star?',
        visualSpeech: 'Please spot the mixed-up arrow!',
        scene: 1,
      },
      {
        emoji: '⬅️☁️🐻⭐',
        title: 'Run the wrong path once',
        body: 'Press Go and watch carefully. Left 3 carries Tuan Tuan from grid 8 to grid 5. The plaza star waits at grid 11, so Tuan Tuan is farther away—not closer.',
        speaker: 'Tuan Tuan',
        dialogue: 'Will Left carry me toward the star or farther away?',
        visualSpeech: 'Watch where I finish.',
        scene: 2,
        direction: { arrow: 'left', target: 'Plaza star' },
      },
      {
        emoji: '🛠️➡️',
        title: 'Swap only the arrow',
        body: 'Tap the Left 3 block in the real workspace. Choose Right. Keep Start, 3, and End exactly as they are—only the arrow changes. Then press Go to test the repaired path.',
        speaker: 'Tuan Tuan',
        dialogue: 'Do not add a block. Just turn my one arrow toward the plaza!',
        visualSpeech: 'Left becomes Right. Three stays three!',
        scene: 4,
        blocks: ['⬅️ Left 3', '➡️ Right 3'],
      },
    ],
    partnerLine: 'You can debug one tiny mistake without changing the whole path!',
    mission:
      'Press Go once to see Left 3 walk away from the plaza. Then tap the Left 3 block and swap it to Right. Keep the number 3, Start, and End unchanged. Press Go again.',
    question: 'Which single part of the path needs to turn around?',
    choices: [],
    retry: 'The plaza star is still on the right. Check which way the one arrow points.',
    successTitle: 'Your repaired arrow is ready to test! ⭐',
    success: 'Only the arrow changed. The three steps, Start, and End stayed in their places.',
    fixTitle: 'Repair one real block',
    fixPrompt: 'Close this card. Tap Left 3 in the real chain, then choose Right. Do not add or remove a block.',
    workspaceIntro: 'No answer button fixes this path. Tap the real Left 3 block and turn only its arrow.',
    fixChoices: [],
    fixRetry: '',
    coach: {
      ready: 'Press Go once. Let’s see where Left 3 finishes.',
      watch: 'Watch whether Left carries me closer to the plaza star.',
      sayFirst: 'The plaza stays on the right.',
      sayThen: 'The plaza stays on the right.',
      hopFirst: 'I followed the arrow.',
      hopThen: 'I followed the arrow.',
      retry: 'I finished at grid 5. Tap Left 3 and turn only the arrow toward the right.',
      fix: 'Tap the real Left 3 block. Keep its 3 and the two other blocks.',
      test: 'Right 3 points to the plaza. Press Go to test your one-block repair!',
      saving: 'Tuan Tuan reached grid 11. I am saving your repaired arrow…',
      complete: 'You changed only Left to Right, and your saved path reached the plaza!',
    },
    coachGoal: {
      label: 'Goal',
      target: '⭐ Reach the plaza star on the RIGHT',
      now: 'Run Left 3 once. Then tap the Left 3 block, choose Right, and press Go again.',
    },
    coachSteps: ['Run Left 3', 'Tap Left 3', 'Choose Right', 'Press Go'],
    logicSteps: [
      { icon: '🚩', label: 'Start', order: 'Keep' },
      { icon: '⬅️', label: 'Turn to Right', order: 'Change' },
      { icon: '🏁', label: 'End', order: 'Keep' },
    ],
    logicWhy: 'The distance was already 3. Only the direction was reversed, so changing Left to Right sends 8 + 3 to the plaza at 11.',
    completionTitle: 'Mission 7 complete! 🛠️⭐',
    completion: 'You ran the wrong path, changed only its arrow from Left 3 to Right 3, saved it, and tested the whole repaired program.',
    completionSteps: [
      { icon: '🚩', label: 'Start', order: 'Keep' },
      { icon: '➡️', label: 'Right 3', order: 'Fixed' },
      { icon: '🏁', label: 'End', order: 'Keep' },
    ],
    completionWhy: 'Only the arrow changed. Right 3 moves from grid 8 to grid 11, where the plaza star waits.',
    next: 'The cloud path is working again. Next, you will make a two-step path of your own.',
  },
  'tsv-s1-a2-s': {
    mode: 'personal-ship',
    lessonId: 'tsv-s1-a2-s',
    hero: {
      name: 'Tuan Tuan',
      role: 'Cloud-path Maker',
      asset: '/story-blocks/tiny-star-village/characters/cloud-bear/resting-happy-v01.png',
    },
    eyebrow: 'Tiny Star Village · Chapter 2 · Mission 8',
    title: 'Make your own two-step path',
    storyPages: [
      {
        emoji: '☁️🐻⭐', title: 'Choose where the story ends',
        body: 'Tuan Tuan starts at grid 8. Put your home star two spaces left at grid 6 or two spaces right at grid 10.',
        speaker: 'Tuan Tuan', dialogue: 'Which home star should my path reach?', scene: 1,
      },
      {
        emoji: '⬅️⬅️➡️➡️', title: 'Build two real arrows',
        body: 'The star buttons move only the star. You must add two one-step arrows in the real workspace. Both arrows must point toward your chosen star.',
        speaker: 'Tuan Tuan', dialogue: 'Place both arrows yourself, then test my path!', scene: 3,
      },
      {
        emoji: '▶️💾✨', title: 'Run and save your route',
        body: 'Press Go. Your story ships only when the saved four-block program carries Tuan Tuan exactly onto the home star you chose.',
        speaker: 'Tuan Tuan', dialogue: 'I will follow your two steps!', scene: 5,
      },
    ],
    partnerLine: 'Your endpoint choice changes the exact program that can finish this story.',
    mission: 'Choose the left or right home star. Then add exactly two matching one-step arrows between Start and End and press Go.',
    question: 'Where will your two-step story end?', choices: [],
    retry: 'Check your star and both arrows. Two Left steps reach grid 6; two Right steps reach grid 10.',
    successTitle: 'Your two-step path is ready!',
    success: 'The star and the two real arrows tell the same route.',
    fixTitle: 'Build your route',
    fixPrompt: 'Choose an endpoint below the stage, then add both arrows in the workspace.',
    workspaceIntro: 'The endpoint buttons never add answer blocks. Build both one-step arrows yourself.',
    fixChoices: [], fixRetry: '',
    coach: {
      ready: 'Choose a home star, then build two arrows.', watch: 'Watch where both one-step arrows carry me.',
      sayFirst: 'Follow your star.', sayThen: 'Follow your star.', hopFirst: 'First step.', hopThen: 'Second step.',
      retry: 'Your saved arrows must land exactly on your chosen star.', fix: 'Add two matching one-step arrows.',
      test: 'Your star and arrows match. Press Go!', saving: 'You arrived. Saving your personal path…',
      complete: 'Your saved two-step story reached your chosen home star!',
    },
    logicSteps: [
      { icon: '⭐', label: 'Choose star', order: 'First' },
      { icon: '⬅️', label: 'Add arrow 1', order: 'Second' },
      { icon: '⬅️', label: 'Add arrow 2', order: 'Third' },
    ],
    logicWhy: 'Two one-step arrows in the same direction move from grid 8 to grid 6 or grid 10.',
    completionTitle: 'Chapter 2 complete! ☁️⭐',
    completion: 'You chose a meaningful endpoint, authored both real arrows, ran the exact route, and saved your personal story.',
    completionSteps: [
      { icon: '🚩', label: 'Start', order: '1' },
      { icon: '⬅️', label: 'One step', order: '2' },
      { icon: '⬅️', label: 'One step', order: '3' },
      { icon: '🏁', label: 'End', order: '4' },
    ],
    completionWhy: 'The runner finished on the selected star and the same exact program was saved on the server.',
    next: 'Tuan Tuan sees Dot Dot sleeping under the rooftop star. Next, discover what wakes Dot Dot.',
  },
};
