// Tiny Star Village A3｜点一点，点点醒来 — Story Blocks mission guides.
// Split out of curriculumGuides.ts to keep every file under the 1000-line
// hard rule in rules/file-organization.md. curriculumGuides.ts stays the
// public module and re-exports the assembled catalogue.

import type { StoryMission } from './types';

export const TSV_A3_MISSIONS: Record<string, StoryMission> = {
  'tsv-s1-a3-h': {
    mode: 'observe-only', lessonId: 'tsv-s1-a3-h', celebrate: false,
    hero: { name: 'Dot Dot', role: 'Rooftop Star Keeper', asset: '/story-blocks/tiny-star-village/characters/dot-dot/standing-calm-v01.png' },
    eyebrow: 'Tiny Star Village · Chapter 3 · Mission 9', title: 'Go cannot wake Dot Dot',
    storyPages: [
      { emoji: '🐱💤', title: 'Dot Dot is sleeping', body: 'Dot Dot sleeps under the rooftop star. The green Go button starts the village, but Dot Dot is waiting for a different start.', speaker: 'Lumilo', dialogue: 'Try Go first. Watch Dot Dot.', scene: 1 },
      { emoji: '▶️😴', title: 'Go makes no response', body: 'Press Go. Dot Dot does not hop or speak because this script waits for a tap, not for Go.', speaker: 'Lumilo', dialogue: 'Go did not wake Dot Dot.', scene: 3, blocks: ['▶️ Go', '😴 No response'] },
      { emoji: '👆🐱', title: 'Try your fingertip', body: 'Tap Dot Dot on the stage. On Tap runs only for the character you touched, so Dot Dot hops and says “I’m awake!”.', speaker: 'Dot Dot', dialogue: 'A gentle tap wakes me!', scene: 5, blocks: ['👆 On Tap', '🦘 Hop + Say'] },
    ],
    partnerLine: 'Your real touch can be the reason a story begins.',
    mission: 'Press Go once and notice Dot Dot stays asleep. Then tap Dot Dot on the stage and watch the different event run.',
    question: 'What woke Dot Dot?', choices: [{ id: 'go', label: '▶️ The Go button', correct: false }, { id: 'tap', label: '👆 My tap on Dot Dot', correct: true }],
    retry: 'Try the two starts again: Go first, then tap Dot Dot.', successTitle: 'You found a different start!', success: 'Only your tap ran Dot Dot’s On Tap script.',
    fixTitle: 'Story Hook complete', fixPrompt: 'Keep the finished On Tap program. You will build a response in the next mission.', workspaceIntro: 'Do not change the blocks. Compare Go with a real tap on Dot Dot.', fixChoices: [], fixRetry: '',
    coach: { ready: 'Press Go first. Watch Dot Dot.', watch: 'Did Go make Dot Dot hop or speak?', sayFirst: 'Dot Dot speaks after a tap.', sayThen: 'Dot Dot speaks after a tap.', hopFirst: 'Dot Dot hops after a tap.', hopThen: 'Dot Dot hops after a tap.', retry: 'Now tap Dot Dot directly on the stage.', fix: 'No fix yet. Name what started the response.', test: 'Press Go, then tap Dot Dot.', saving: 'Your observation is saved with the unchanged program.', complete: 'Your tap—not Go—woke Dot Dot!' },
    logicSteps: [{ icon: '▶️', label: 'Go', order: 'No response' }, { icon: '👆', label: 'Tap Dot Dot', order: 'Starts' }, { icon: '🦘', label: 'Hop and say', order: 'Response' }],
    logicWhy: 'A script beginning with On Tap waits for that character to be touched.', completionTitle: 'Story Hook complete · You discovered On Tap!', completion: 'You ran Go, then used a real stage tap and identified the event that made Dot Dot respond.', completionSteps: [{ icon: '▶️', label: 'Try Go', order: 'First' }, { icon: '👆', label: 'Tap Dot Dot', order: 'Then' }, { icon: '💬', label: 'Name the cause', order: 'Explain' }], completionWhy: 'The exact saved script starts with On Tap, so Go cannot run it.', next: 'Next, add one visible response after On Tap in A3-B.',
  },
  'tsv-s1-a3-b': {
    mode: 'complete', lessonId: 'tsv-s1-a3-b', celebrate: true,
    hero: { name: 'Dot Dot', role: 'Rooftop Star Keeper', asset: '/story-blocks/tiny-star-village/characters/dot-dot/standing-calm-v01.png' },
    eyebrow: 'Tiny Star Village · Chapter 3 · Mission 10', title: 'Build a tap response',
    storyPages: [
      { emoji: '👆🧩', title: 'On Tap is waiting', body: 'Dot Dot has an On Tap start and an End, but nothing visible happens between them yet.', speaker: 'Dot Dot', dialogue: 'Give my tap a response!', scene: 1 },
      { emoji: '🦘💬', title: 'Choose a visible response', body: 'Add Hop 1 or a Say block in the real workspace. You may add both, but On Tap must stay first.', speaker: 'Lumilo', dialogue: 'Your block decides what a tap will do.', scene: 3, blocks: ['👆 On Tap', '🦘 Hop 1 or 💬 Say'] },
      { emoji: '🐱👆✨', title: 'Tap Dot Dot to test', body: 'The green Go button cannot start this script. Save your chain, then tap Dot Dot on the stage to run your response.', speaker: 'Dot Dot', dialogue: 'Tap me when your block is ready!', scene: 5 },
    ],
    partnerLine: 'You choose a real response, and your fingertip starts it.',
    mission: 'Add Hop 1 or Say between On Tap and End. Wait for it to save, then tap Dot Dot on the stage.',
    question: 'What should Dot Dot do when tapped?', choices: [], retry: 'Keep On Tap first. Add Hop 1 or a non-empty Say before End.',
    successTitle: 'Your tap response is ready!', success: 'The saved chain starts with On Tap and contains your visible response.',
    fixTitle: 'Build one real response', fixPrompt: 'Close this card. Add Hop 1 or Say in the real chain, then tap Dot Dot.',
    workspaceIntro: 'No answer button builds this scene. Add a real response block between On Tap and End.', fixChoices: [], fixRetry: '',
    coach: {
      ready: 'Add Hop 1 or Say after On Tap.', watch: 'Go cannot start this chain. Tap Dot Dot instead.',
      sayFirst: 'Dot Dot can speak after your tap.', sayThen: 'Your tap started the saved Say block.',
      hopFirst: 'Dot Dot can hop after your tap.', hopThen: 'Your tap started the saved Hop block.',
      retry: 'Keep On Tap first and add one visible response.', fix: 'Add Hop 1 or a non-empty Say before End.',
      test: 'Your tap response is ready. Wait for Saved, then tap Dot Dot!', saving: 'Your real tap ran the response. Saving the exact chain…',
      complete: 'Your saved On Tap story responded to a real tap!',
    },
    logicSteps: [{ icon: '👆', label: 'On Tap', order: 'First' }, { icon: '🦘', label: 'Hop or Say', order: 'Response' }, { icon: '🏁', label: 'End', order: 'Last' }],
    logicWhy: 'On Tap listens for a touch on Dot Dot, then runs the response blocks below it.',
    completionTitle: 'Mission 10 complete! 👆✨', completion: 'You added a visible response, saved it, and used a real stage tap to run it.',
    completionSteps: [{ icon: '👆', label: 'On Tap', order: 'Start' }, { icon: '🦘', label: 'Your response', order: 'Run' }, { icon: '💾', label: 'Saved', order: 'Proof' }],
    completionWhy: 'The server-saved chain kept On Tap first, and the real tap ran your chosen visible response.', next: 'Next, repair a tap script whose event block is wrong.',
  },
  'tsv-s1-a3-d': {
    mode: 'observe-fix', lessonId: 'tsv-s1-a3-d', celebrate: true,
    hero: { name: 'Dot Dot', role: 'Rooftop Star Keeper', asset: '/story-blocks/tiny-star-village/characters/dot-dot/standing-calm-v01.png' },
    eyebrow: 'Tiny Star Village · Chapter 3 · Mission 11', title: 'The wrong start hat',
    storyPages: [
      { emoji: '🐱🎩', title: 'Dot Dot has the wrong hat', body: 'The response is ready, but its first block says Start. That hat listens for Go, not a fingertip.', speaker: 'Dot Dot', dialogue: 'Why does your tap do nothing?', scene: 1 },
      { emoji: '👆😴', title: 'Find the bug', body: 'Tap Dot Dot on the real stage first. Nothing happens because the event block does not match your action.', speaker: 'Lumilo', dialogue: 'The response is fine. Check the first block.', scene: 3, blocks: ['🚩 Start', '🦘 Hop 1 → End'] },
      { emoji: '👆🔁', title: 'Swap only the event', body: 'Tap the Start block and replace it with On Tap. Keep Hop 1 and End exactly where they are, then tap Dot Dot again.', speaker: 'Dot Dot', dialogue: 'Give me my tap hat!', scene: 5, blocks: ['👆 On Tap', '🦘 Hop 1 → End'] },
    ],
    partnerLine: 'A matching event makes the same response wake up.',
    mission: 'Tap Dot Dot once to see no response. Replace only Start with On Tap, wait for Saved, then tap Dot Dot again.',
    question: 'Which start listens for your fingertip?', choices: [], retry: 'Tap Dot Dot first. Then change only the first event block.',
    successTitle: 'The event matches!', success: 'Your real tap ran the unchanged Hop response.',
    fixTitle: 'Repair one event block', fixPrompt: 'Close this card, tap Start, and choose On Tap. Do not add or remove response blocks.',
    workspaceIntro: 'First prove the tap does nothing. Then repair only the first block in the real chain.', fixChoices: [], fixRetry: '',
    coach: { ready: 'Tap Dot Dot first. Watch for no response.', watch: 'The tap did nothing. Which first block listens for touch?', sayFirst: 'Keep the response unchanged.', sayThen: 'Keep the response unchanged.', hopFirst: 'Hop is already correct.', hopThen: 'The repaired tap ran Hop.', retry: 'Tap Dot Dot before opening the wrong Start block.', fix: 'Now tap Start and replace it with On Tap.', test: 'Saved? Tap Dot Dot again to test the repair.', saving: 'Your repaired event ran. Saving the exact chain…', complete: 'On Tap now wakes Dot Dot!' },
    logicSteps: [{ icon: '👆', label: 'Tap Dot Dot', order: 'Find bug' }, { icon: '🔁', label: 'Start → On Tap', order: 'Fix one' }, { icon: '👆', label: 'Tap again', order: 'Test' }],
    logicWhy: 'The first event block decides which action starts the response.',
    completionTitle: 'Mission 11 complete! 🎩✨', completion: 'You proved the tap failed, replaced only the wrong event, saved it, and ran the response with a real tap.',
    completionSteps: [{ icon: '👆', label: 'No response', order: 'Before' }, { icon: '🔁', label: 'On Tap', order: 'Repair' }, { icon: '🦘', label: 'Hop runs', order: 'After' }],
    completionWhy: 'The server-saved program is exactly On Tap → Hop 1 → End, and the real tap finished it.', next: 'Next, design your own tap surprise in A3-S.',
  },
  'tsv-s1-a3-s': {
    mode: 'complete', lessonId: 'tsv-s1-a3-s', celebrate: true,
    hero: { name: 'Your secret friend', role: 'Tap Surprise Maker', asset: '/story-blocks/tiny-star-village/characters/dot-dot/standing-calm-v01.png' },
    eyebrow: 'Tiny Star Village · Chapter 3 · Mission 12', title: 'My tap surprise',
    storyPages: [
      { emoji: '🌟👀', title: 'Hide a rooftop secret', body: 'The rooftop star needs a surprise that a friend can discover by tapping.', speaker: 'Lumilo', dialogue: 'Choose who will keep your secret.', scene: 1 },
      { emoji: '🐱🐻⭐', title: 'Choose your character', body: 'Pick Dot Dot, Tuan Tuan, or Lumilo. This changes the real saved character but never adds an answer block.', speaker: 'Lumilo', dialogue: 'Your character, your story.', scene: 3 },
      { emoji: '👆✨', title: 'Build one surprise', body: 'Add exactly one Hop 1, Grow 1, or preset Say between On Tap and End. Save it, then tap the character to test.', speaker: 'Your friend', dialogue: 'Can someone discover me?', scene: 5, blocks: ['👆 On Tap', '✨ One response → End'] },
    ],
    partnerLine: 'Your choice changes both the saved character and its secret response.',
    mission: 'Choose one character, add exactly one visible response, wait for Saved, then tap the character.',
    question: 'What will your secret character do?', choices: [], retry: 'Keep On Tap first and End last. Add exactly one Hop 1, Grow 1, or preset Say.',
    successTitle: 'Your tap surprise is ready!', success: 'A real tap ran your saved character and response.',
    fixTitle: 'Build your own surprise', fixPrompt: 'Close this card, choose a character, and add one real response block.',
    workspaceIntro: 'Character buttons change only the saved character. You must add the response in the real editor.', fixChoices: [], fixRetry: '',
    coach: { ready: 'Choose your secret character, then add one response.', watch: 'Tap your chosen character only after the chain is ready.', sayFirst: 'Choose a preset message.', sayThen: 'Your tap revealed the saved message.', hopFirst: 'Hop 1 makes a small surprise.', hopThen: 'Your tap ran the saved hop.', retry: 'Use exactly one Hop 1, Grow 1, or preset Say.', fix: 'Build the response in the real chain.', test: 'Saved? Tap your secret character now.', saving: 'Your tap surprise ran. Saving the exact story…', complete: 'A friend can now discover your tap surprise!' },
    logicSteps: [{ icon: '🐱', label: 'Choose friend', order: 'Mine' }, { icon: '👆', label: 'On Tap', order: 'Start' }, { icon: '✨', label: 'One response', order: 'Secret' }],
    logicWhy: 'On Tap waits for a touch, then runs the one response you authored.',
    completionTitle: 'Chapter 3 complete! 👆✨', completion: 'You chose a character, authored one visible response, saved it, and ran it with a real tap.',
    completionSteps: [{ icon: '🐱', label: 'Character', order: 'Choose' }, { icon: '🧩', label: 'Response', order: 'Build' }, { icon: '👆', label: 'Tap', order: 'Reveal' }],
    completionWhy: 'The server-saved project contains your selected character and exact On Tap surprise, and the real runner finished it.', next: 'Dot Dot spots the breakfast cart. Next, predict how far it should travel.',
  },
};
